// Shared "export what's on screen" helpers — a real .xlsx download and a branded, print-ready PDF
// report. Every page builds the same simple shape (a title + column headers + rows, reflecting the
// current search / filter / sort) and hands it here, so Excel and PDF look and behave consistently
// everywhere. Rows are plain strings/numbers already formatted for display.

import { downloadXlsxTemplate } from './xlsxTemplate'
import { today } from './model'

export interface ViewExport {
  title: string        // e.g. "Tasks — Today"
  subtitle?: string    // e.g. active filters, or the area/collection name
  headers: string[]
  rows: (string | number)[][]
  filenameBase: string // e.g. "daybook-tasks-today"
}

export function exportViewToXlsx(v: ViewExport) {
  downloadXlsxTemplate(`${v.filenameBase}-${today()}.xlsx`, v.title.replace(/[^\w -]/g, '').slice(0, 31) || 'Export', [v.headers, ...v.rows])
}

const esc = (s: unknown) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

// Opens the browser print dialog on a nicely designed, self-contained report (Save as PDF from
// there). Rendered in a hidden iframe so it's never blocked like a popup, and removed after.
export function exportViewToPdf(v: ViewExport) {
  const dateStr = new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  const thead = v.headers.map(h => `<th>${esc(h)}</th>`).join('')
  const tbody = v.rows.map(r => `<tr>${v.headers.map((_, i) => `<td>${esc(r[i])}</td>`).join('')}</tr>`).join('')
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${esc(v.title)}</title>
<style>
  @page { size: A4 landscape; margin: 14mm 12mm; }
  * { box-sizing: border-box; }
  html, body { margin: 0; }
  body { font-family: Georgia, 'Times New Roman', serif; color: #1b2016; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .brand { font-family: Arial, Helvetica, sans-serif; font-size: 11px; letter-spacing: .2em; text-transform: uppercase; color: #4a6b3f; font-weight: 700; }
  h1 { font-size: 25px; margin: 3px 0 2px; color: #22331d; }
  .sub { font-family: Arial, Helvetica, sans-serif; font-size: 12.5px; color: #5f6b55; margin: 0 0 2px; }
  .meta { font-family: Arial, Helvetica, sans-serif; font-size: 11px; color: #949a88; }
  .rule { height: 3px; background: #2e4600; border-radius: 2px; margin: 11px 0 15px; }
  table { width: 100%; border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; font-size: 10.5px; }
  thead th { background: #2e4600; color: #fff; text-align: left; padding: 7px 9px; font-size: 9.5px; letter-spacing: .05em; text-transform: uppercase; }
  tbody td { padding: 6px 9px; border-bottom: 1px solid #e6e3d7; vertical-align: top; }
  tbody tr:nth-child(even) { background: #f6f4ec; }
  thead { display: table-header-group; }
  tr { break-inside: avoid; }
  .foot { margin-top: 12px; font-family: Arial, Helvetica, sans-serif; font-size: 10px; color: #949a88; }
</style></head>
<body>
  <div class="brand">Daybook</div>
  <h1>${esc(v.title)}</h1>
  ${v.subtitle ? `<div class="sub">${esc(v.subtitle)}</div>` : ''}
  <div class="meta">${dateStr} · ${v.rows.length} ${v.rows.length === 1 ? 'item' : 'items'}</div>
  <div class="rule"></div>
  ${v.rows.length ? `<table><thead><tr>${thead}</tr></thead><tbody>${tbody}</tbody></table>` : '<p style="font-family:Arial;color:#949a88;font-size:12px">Nothing to show for the current filters.</p>'}
  <div class="foot">Generated by Daybook · ${dateStr}</div>
</body></html>`

  const iframe = document.createElement('iframe')
  iframe.setAttribute('aria-hidden', 'true')
  Object.assign(iframe.style, { position: 'fixed', right: '0', bottom: '0', width: '0', height: '0', border: '0' })
  iframe.onload = () => {
    const w = iframe.contentWindow
    if (!w) return
    w.focus()
    w.print()
    setTimeout(() => iframe.remove(), 1500)
  }
  iframe.srcdoc = html
  document.body.appendChild(iframe)
}
